// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#include "host.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `rpi`

__attribute__((__import_module__("rpi"), __import_name__("host-alsa-capture-init")))
extern int32_t __wasm_import_rpi_host_alsa_capture_init(void);

__attribute__((__import_module__("rpi"), __import_name__("host-read-audio-block-i16")))
extern void __wasm_import_rpi_host_read_audio_block_i16(int32_t, uint8_t *);

__attribute__((__import_module__("rpi"), __import_name__("host-snd-pcm-close")))
extern void __wasm_import_rpi_host_snd_pcm_close(void);

__attribute__((__import_module__("rpi"), __import_name__("host-printf")))
extern void __wasm_import_rpi_host_printf(uint8_t *, size_t);

__attribute__((__import_module__("rpi"), __import_name__("host-sin")))
extern double __wasm_import_rpi_host_sin(double);

__attribute__((__import_module__("rpi"), __import_name__("host-cos")))
extern double __wasm_import_rpi_host_cos(double);

// Exported Functions from `host`


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void host_list_s16_free(host_list_s16_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    int16_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void host_string_set(host_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void host_string_dup(host_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void host_string_dup_n(host_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void host_string_free(host_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

int32_t rpi_host_alsa_capture_init(void) {
  int32_t ret = __wasm_import_rpi_host_alsa_capture_init();
  return ret;
}

void rpi_host_read_audio_block_i16(uint32_t n, host_list_s16_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_rpi_host_read_audio_block_i16((int32_t) (n), ptr);
  *ret = (host_list_s16_t) { (int16_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

void rpi_host_snd_pcm_close(void) {
  __wasm_import_rpi_host_snd_pcm_close();
}

void rpi_host_printf(host_string_t *msg) {
  __wasm_import_rpi_host_printf((uint8_t *) (*msg).ptr, (*msg).len);
}

double rpi_host_sin(double x) {
  double ret = __wasm_import_rpi_host_sin(x);
  return ret;
}

double rpi_host_cos(double x) {
  double ret = __wasm_import_rpi_host_cos(x);
  return ret;
}

__attribute__((__export_name__("run")))
int32_t __wasm_export_exports_host_run(void) {
  int32_t ret = exports_host_run();
  return ret;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_host(void);
__attribute__((used))
void __component_type_object_force_link_host_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_host();
}
