// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#ifndef __BINDINGS_HOST_H
#define __BINDINGS_HOST_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct host_string_t {
  uint8_t*ptr;
  size_t len;
} host_string_t;

typedef struct {
  int16_t *ptr;
  size_t len;
} host_list_s16_t;

// Imported Functions from `rpi`
extern int32_t rpi_host_alsa_capture_init(void);
extern void rpi_host_read_audio_block_i16(uint32_t n, host_list_s16_t *ret);
extern void rpi_host_snd_pcm_close(void);
extern void rpi_host_printf(host_string_t *msg);
extern double rpi_host_sin(double x);
extern double rpi_host_cos(double x);

// Exported Functions from `host`
int32_t exports_host_run(void);

// Helper Functions

void host_list_s16_free(host_list_s16_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void host_string_set(host_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void host_string_dup(host_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void host_string_dup_n(host_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void host_string_free(host_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
